TFP-1022 Avslagsbrev for svangerskapspenger
navikt/fp-formidling pull request #1579
Opened 2021-12-03 15:15 UTC by AnjaAalerud

Nytt brev for avslag svangerskapspenger. Jeg har i tilegg lagt til SvpMapperUtil for å samle det som er felles for avslag og opphør på svp.

2021-12-04 10:58 UTC, mrsladek approved these changes
Bra jobbet - det er en del kode som er felles for FP og SVP som bør kanskje på sikt flyttes til felles mapper klasser (innhenting av uttak, første/siste stønadsdag etc).

2021-12-06 10:19 UTC, jejohnsen requested changes

2021-12-06 10:19 UTC, jejohnsen commented on domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/SvangerskapspengerAvslagDokumentdataMapper.java
> +        fellesBuilder.medBrevDato(dokumentFelles.getDokumentDato() != null ? formaterDato(dokumentFelles.getDokumentDato(), behandling.getSpråkkode()) : null);
Her må du bruke språkkode som er definert på linje 63

2021-12-06 10:19 UTC, jejohnsen commented on domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/SvangerskapspengerOpphørDokumentdataMapper.java
>              fellesBuilder.medBrevDato(dokumentFelles.getDokumentDato() != null ? formaterDato(dokumentFelles.getDokumentDato(), behandling.getSpråkkode()) : null);
Her også

2021-12-06 10:19 UTC, jejohnsen commented on integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/SvangerskapspengerAvslagDokumentdata.java
> +        return Objects.hash(felles, årsak, stønadsdatoFom, antallArbeidsgivere, halvG, lovhjemmel, klagefristUker);
Mangler erSøkerDød og mottattDato

2021-12-06 11:36 UTC, AnjaAalerud commented on domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/SvangerskapspengerAvslagDokumentdataMapper.java
> +        fellesBuilder.medBrevDato(dokumentFelles.getDokumentDato() != null ? formaterDato(dokumentFelles.getDokumentDato(), behandling.getSpråkkode()) : null);
done

2021-12-06 11:36 UTC, AnjaAalerud commented on domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/opphørsvp/SvangerskapspengerOpphørDokumentdataMapper.java
>              fellesBuilder.medBrevDato(dokumentFelles.getDokumentDato() != null ? formaterDato(dokumentFelles.getDokumentDato(), behandling.getSpråkkode()) : null);
done

2021-12-06 11:37 UTC, AnjaAalerud commented on integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/SvangerskapspengerAvslagDokumentdata.java
> +        return Objects.hash(felles, årsak, stønadsdatoFom, antallArbeidsgivere, halvG, lovhjemmel, klagefristUker);
done

2021-12-06 15:11 UTC, jejohnsen approved these changes

2021-12-08 12:56 UTC, merged