TFP-4741 Endret håndtering av død innvilgelse fp
navikt/fp-formidling pull request #1592
Opened 2021-12-09 20:11 UTC by AnjaAalerud

Endret slik at dersom alle barna er døde settes dødsdato, ellers ikke. Det betyr at hvis det er gjenlevende barn så vil innvilgelse foreldrepenger trigges, og brev sendes ut uten forklaring om at flerbarnsdager blir trukket pga barn som dør. Saksbehandler må eventuelt overstyre dersom det er behov for ytterligere beskrivelse. Når løsningen har logikk for død kan vi også vurdere automatiske tekster

2021-12-09 22:45 UTC, mrsladek commented
Dette ser bra ut :)

2021-12-09 22:45 UTC, mrsladek approved these changes

2021-12-10 11:20 UTC, jejohnsen approved these changes

2021-12-10 11:21 UTC, jejohnsen requested changes

2021-12-10 11:21 UTC, jejohnsen commented on dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/familiehendelse/FamilieHendelse.java
>                             FamilieHendelseType familieHendelseType,
Så ikke denne før Sonar hadde påpekt, men mangler tydeligvis å assigne den?

2021-12-10 13:38 UTC, AnjaAalerud commented on dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/familiehendelse/FamilieHendelse.java
>                             FamilieHendelseType familieHendelseType,
har oppdatert

2021-12-10 13:42 UTC, jejohnsen approved these changes

2021-12-10 13:43 UTC, merged