Liten ryddeaksjon i dtos
navikt/fp-formidling pull request #1947
Opened 2022-05-26 20:25 UTC by jolarsen

Hente gjeldende dekningsgrad fra FagsakDto (og fjerne bruk av ytelsefordeling)
Fjerne ubrukte Dtos - DokumentMalType og Beregningsgrunnlag
Forberede bruk av ressurslenke for beregningsgrunnlag
Legge til utenMinsterett

2022-05-26 23:19 UTC, mrsladek submitted a review, later dismissed
Beregningsgrunnlag har en egen dedisert REST endepunkt og resourcelenker skal ikke brukes der. Om ikke lenge får formidling også flere endre dediserte endepunkter som erstatter alle de fra ressurs lenker.

2022-05-27 08:07 UTC, AnjaAalerud approved these changes

2022-05-27 08:12 UTC, AnjaAalerud commented
Jeg ser at Michal har kommentert at vi skal erstatte alle ressurslenker med egne endepunkter..og det er nok bedre siden vi da kan be om kun den informasjonen vi trenger og ikke alt... Men da bør vi kanskje fjerne at beregningsgrunnlag ligger med som ressurslenke på behandlingDto ? Det er litt forvirrende hva som gjelder.

2022-05-27 08:13 UTC, AnjaAalerud requested changes
Jeg ser at Michal har kommentert at vi skal erstatte alle ressurslenker med egne endepunkter..og det er nok bedre siden vi da kan be om kun den informasjonen vi trenger og ikke alt... Men da bør vi kanskje fjerne at beregningsgrunnlag ligger med som ressurslenke på behandlingDto ? Det er litt forvirrende hva som gjelder.

2022-05-27 08:46 UTC, jolarsen commented
Hm, jeg endrer navn på ressurslenken til "beregningsgrunnlag-formidling" for å vise et eget navnerom, tilsvarende soknad/verge-backend.  Ressurslenker er navnerom og vi bør begynne der for å ha oversikten.
Vi bruker ressurslenker i frontend/los/tilbake/formidling og jeg synes vi skal fortsette med det inntil vi er enig om noe annet.
Dette handler mest om vedlikehold av fpsak som provider ressurslenker og den konvensjonen som Jan Erik innførte. Dere som har åpnet regnearket ArbBokSakRest vil kunne se oversikt over hvem som bruker hva og hvilke direkte endepunktrefs som finnes.
@mrsladek  jeg ser at det er innført et direkte kall til et dedikert bg-endepunkt og jeg ser at det ikke var ryddet i det gamle. Jeg synes vi skal ta en prosess før vi endrer praksis, så hele teamet er med på det. 
@AnjaAalerud det er ikke et valg mellom enten ressurslenker eller endepunkt. Det er provider (fpsak) som bestemmer navn på ressurslenkene og den kan lett ha xyz og xyz-backend og xyz-formidling som går til ulike (eller samme) endepunkt.

2022-05-27 09:12 UTC, AnjaAalerud approved these changes
Det kunne være fint med en felles prat om hva vi ser for oss i fremtiden her - fordeler og ulemper og hva som er lurt gå videre med

2022-05-27 09:42 UTC, merged