TFP-3847 Lagt inn avslagsbrev for engangsstønad i fp-dokgen
navikt/fp-formidling pull request #843
Opened 2020-11-19 15:18 UTC by AnjaAalerud

2020-11-19 16:18 UTC, jejohnsen requested changes

2020-11-19 16:18 UTC, jejohnsen commented on dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/kodeverk/kodeverdi/DokumentMalTypeKode.java
> +    //fp-dokgen
Hvorfor endrer du det? Da blir det ikke konsistent med oppdelingskommentaren de andre stedene (DokumentMalType her og i Fpsak)

2020-11-19 16:18 UTC, jejohnsen commented on domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/AvslagEngangsstønadDokumentDataMapper.java
> +        if(vilkårType.equals(VilkårType.ADOPSJONSVILKÅRET_ENGANGSSTØNAD) || vilkårType.equals(VilkårType.FØDSELSVILKÅRET_MOR) && !behandling.erRevurdering()) {
Alltid lurt å sette konstanten/enumen som ikke kan være null først i equals() (gjelder alle nedover her)

2020-11-19 16:18 UTC, jejohnsen commented on integrasjon/dokgen-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/dokgen/dto/EngangsstønadAvslagDokumentData.java
> +    private boolean førstegangsBehandling;
Liten B, ref kommentar i Fp-dokgen

2020-11-20 09:15 UTC, AnjaAalerud commented on dokumentlager/domene/src/main/java/no/nav/foreldrepenger/melding/kodeverk/kodeverdi/DokumentMalTypeKode.java
> +    //fp-dokgen
ok

2020-11-20 09:18 UTC, AnjaAalerud commented on domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevmapper/brev/AvslagEngangsstønadDokumentDataMapper.java
> +        if(vilkårType.equals(VilkårType.ADOPSJONSVILKÅRET_ENGANGSSTØNAD) || vilkårType.equals(VilkårType.FØDSELSVILKÅRET_MOR) && !behandling.erRevurdering()) {
utført

2020-11-21 12:33 UTC, jejohnsen approved these changes

2020-11-21 15:33 UTC, merged