TFP-3964 Flytter innsynsbrevet til fp-dokgen, og legger inn en proses…
navikt/fp-formidling pull request #965
Opened 2021-01-27 13:42 UTC by AnjaAalerud

…stask for å tilknytte vedlegg og prosesstask for å ferdigstille journalføringen etter vedlegg er tilknyttet.

2021-01-27 17:54 UTC, jejohnsen requested changes

2021-01-28 08:00 UTC, AnjaAalerud commented on domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokgenLanseringTjeneste.java
> +            DokumentMalType.INNSYNSKRAV_SVAR, DokumentMalType.INNSYN_SVAR);
Ja, den gamle koden er hardkodet i front end

2021-01-29 10:03 UTC, AnjaAalerud commented on domenetjenester/brevbestiller/src/main/java/no/nav/foreldrepenger/melding/brevbestiller/impl/DokgenBrevproduksjonTjeneste.java
> +                leggTilVedleggOgFerdigstillForsendelse(dokumentHendelse.getBehandlingUuid(), journalpostId);
Enig. Jeg har endret.

2021-01-29 10:28 UTC, jejohnsen requested changes

2021-01-29 10:28 UTC, jejohnsen commented on domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/InnsynDokumentDataMapperTest.java
> +class InnsynDokumentDataMapperTest {
Fortsatt stor D

2021-01-29 10:28 UTC, jejohnsen commented on integrasjon/journal-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/journal/FerdigstillJournalpostTjeneste.java
> +/*package no.nav.foreldrepenger.melding.integrasjon.journal;
Hvorfor er denne kommentert ut? Hvis den skal utgå må klassen slettes.

2021-01-29 10:34 UTC, AnjaAalerud commented on integrasjon/journal-klient/src/main/java/no/nav/foreldrepenger/melding/integrasjon/journal/FerdigstillJournalpostTjeneste.java
> +/*package no.nav.foreldrepenger.melding.integrasjon.journal;
ja, det var meningen å slette den..

2021-01-29 10:35 UTC, AnjaAalerud commented on domenetjenester/brevbestiller/src/test/java/no/nav/foreldrepenger/melding/brevmapper/brev/InnsynDokumentDataMapperTest.java
> +class InnsynDokumentDataMapperTest {
puh.. :) fjernet

2021-01-29 10:41 UTC, jejohnsen approved these changes

2021-01-29 10:46 UTC, merged